#!/bin/sh -e

# Because I'm too lazy to make this script generic
if [ "$USER" != "shoumodip" ]; then
    echo $(tput setaf 1 && tput bold)'ERROR: $USER must be `shoumodip`'$(tput sgr0)
    exit 1
fi

if [ ! -d "$HOME/code/shoumodip/setup" ]; then
    echo $(tput setaf 1 && tput bold)'ERROR: ~/code/shoumodip/setup does not exist'$(tput sgr0)
    exit 1
fi

cd ~/code/shoumodip/setup

if [ "$1" = "push" ]; then
    xbps-query -m | sed 's/^\([^ ]*\)-.*/\1/' > packages.txt

    if [ $(git status -s | wc -l) -gt 0 ]; then
        git add -A
        git commit -m "Autocommit $(date '+%H:%M:%S %d/%m/%y')"
        git push origin main
    fi
else
    # Adhere to the XDG directory standards
    mkdir -p ~/.local/bin ~/.config ~/.cache
    rm ~/.*bash*

    sudo sed -i 's/^# \(%wheel ALL=(ALL) NOPASSWD: ALL\)/\1/g' /etc/sudoers
    sudo sed -i 's/^\(GETTY_ARGS\)=.*/\1="--autologin shoumodip"/g' /etc/sv/agetty-tty1/conf
    sudo sed -i 's/^\(GRUB_TIMEOUT\)=.*/\1=0/g' /etc/default/grub

    git submodule update --init --recursive
    sudo update-grub
    sudo xbps-install -y $(cat packages.txt)

    # Magnifier and Screenshot tool: https://github.com/shoumodip/thono
    if [ ! -d ~/code/shoumodip/thono ]; then
        git clone https://github.com/shoumodip/thono ~/code/shoumodip/thono
        cd ~/code/shoumodip/thono
        cc -o make make.c
        ./make
        ln -sf $PWD/thono ~/.local/bin/
    fi

    sudo ln -sf /etc/sv/dbus /var/service/
    stow -vt ~ */

    # Prevent ~/.bash_history
    export XDG_CACHE_HOME="$HOME/.cache"
    export HISTFILE="~/.cache/history"

    echo $(tput setaf 2 && tput bold)'SUCCESS: Press ^D to finish'$(tput sgr0)
fi
