#!/bin/sh -e

if [ "$USER" != "shoumodip" ]; then
    echo 'ERROR: $USER must be `shoumodip`'
    exit 1
fi

cd ~/code/shoumodip/setup

if [ "$1" = "push" ]; then
    xbps-query -m | sed 's/^\([^ ]*\)-.*/\1/' > packages.txt

    if [ $(git status -s | wc -l) -gt 0 ]; then
        git add -A
        git commit -m "Autocommit $(date '+%H:%M:%S %d/%m/%y')"
        git push origin main
    fi
else
    mkdir -p ~/.local/bin

    sudo sed -i 's/^# \(%wheel ALL=(ALL) NOPASSWD: ALL\)/\1/g' /etc/sudoers
    sudo sed -i 's/^\(GETTY_ARGS\)=.*/\1="--autologin shoumodip"/g' /etc/sv/agetty-tty1/conf
    sudo sed -i 's/^\(GRUB_TIMEOUT\)=.*/\1=0/g' /etc/default/grub

    sudo update-grub
    sudo xbps-install -y $(cat packages.txt)

    if [ ! -d ~/code/shoumodip/thono ]; then
        git clone https://github.com/shoumodip/thono ~/code/shoumodip/thono
        cd ~/code/shoumodip/thono
        cc -o make make.c
        ./make
        ln -sf $PWD/thono ~/.local/bin/
    fi

    sudo ln -sf /etc/sv/dbus /var/service/
    stow -vt ~ */

    echo $(tput setaf 2 && tput bold)'Press ^D to finish. On next login run `rm -rf ~/.*bash*`'
fi
