#!/bin/sh

if ! type magick >/dev/null; then
    echo "Error: ImageMagick is not installed"
    exit 1
fi

ls *.webp 2>/dev/null | while IFS= read -r f
do
    echo "Converting $f..."
    magick "$f" "$(basename "$f" ".webp").png"
done

rm -f *.webp
