#! /bin/sh

picom &
sxhkd &
xsetroot -cursor_name left_ptr &
xwallpaper --zoom ~/Pictures/wallpaper.png &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config window_gap 5
bspc config border_width 2
bspc config single_monocle true
bspc config borderless_monocle true
