#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config window_gap 5
bspc config border_width 2
bspc config normal_border_color "#282828"
bspc config focused_border_color "#928374"

bspc rule -a Wrapper-2.0 state=floating border=off focus=on

sxhkd &
picom --backend glx &
xsetroot -cursor_name left_ptr &

~/.local/share/wallpaper &
