#!/bin/bash
. "$HOME/Software/msvc/bin/x64/msvcenv.sh"
export WINEPATH="$WINEPATH;Z:\\home\\$USER\\Software\\tools-win32"
export WINEPATH="$WINEPATH;Z:\\home\\$USER\\Software\\curl-win32\\bin"
export WINEPATH="$WINEPATH;Z:\\home\\$USER\\Software\\clang-win32\\bin"
export WINEPATH="$WINEPATH;Z:\\home\\$USER\\Software\\odin-win32"
/usr/bin/wineconsole $@
