#!/bin/sh

ENV_CACHE_BAT_PATH="$HOME/.cache/vcvars64.bat"
ENV_CACHE_TXT_PATH="$HOME/.cache/vcvars64.txt"

if [ -f "$ENV_CACHE_BAT_PATH" ]; then
    wine cmd /c "call Z:$ENV_CACHE_BAT_PATH && cmd"
    exit
fi

if [ -f "$ENV_CACHE_TXT_PATH" ]; then
    echo "@echo off" > "$ENV_CACHE_BAT_PATH"
    sed 's/^/set /' "$ENV_CACHE_TXT_PATH" >> "$ENV_CACHE_BAT_PATH"
    rm "$ENV_CACHE_TXT_PATH"
    wine cmd /c "call Z:$ENV_CACHE_BAT_PATH && cmd"
    exit
fi

env -i \
    HOME="$HOME" \
    XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
    WINEDEBUG="$WINEDEBUG" \
    wine cmd /c "call Z:$HOME/Software/msvc/VC/Auxiliary/Build/vcvars64.bat && set > Z:$ENV_CACHE_TXT_PATH && cmd"
